apiVersion: apps/v1
kind: Deployment
metadata:
  name: getos-api
  namespace: oficina
  labels:
    app.kubernetes.io/name: getos-api
    app.kubernetes.io/part-of: techchallenge-oficina
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: getos-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: getos-api
        app.kubernetes.io/part-of: techchallenge-oficina
    spec:
      imagePullSecrets:
        - name: ecr-regcred
      containers:
        - name: getos-api
          image: 903936907231.dkr.ecr.us-east-1.amazonaws.com/techchallenge-oficina-getos:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: getos-api-config
            - secretRef:
                name: getos-api-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
