apiVersion: v1
kind: Secret
metadata:
  name: ecr-regcred
  namespace: oficina
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "903936907231.dkr.ecr.us-east-1.amazonaws.com": {
          "username": "AWS",
          "password": "",
          "auth": ""
        }
      }
    }
