<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TechChallenge.Oficina.Application\TechChallenge.Oficina.Application.csproj" />
    <ProjectReference Include="..\TechChallenge.Oficina.Infra.Data\TechChallenge.Oficina.Infra.Data.csproj" />
    <ProjectReference Include="..\TechChallenge.Oficina.Infra\TechChallenge.Oficina.Infra.csproj" />
    <ProjectReference Include="..\TechChallenge.Oficina.Infra.Email\TechChallenge.Oficina.Infra.Email.csproj" />
  </ItemGroup>

</Project>
