apiVersion: v1
kind: Secret
metadata:
  name: ecr-regcred
  namespace: oficina
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "903936907231.dkr.ecr.us-east-1.amazonaws.com": {
          "username": "AWS",
          "password": "COLE_AQUI_O_TOKEN_PURO_DO_AWS_ECR",
          "auth": "COLE_AQUI_BASE64_DE_AWS_DOIS_PONTOS_TOKEN"
        }
      }
    }
