apiVersion: v1
kind: Secret
metadata:
  name: createos-api-secret
  namespace: oficina
  labels:
    app.kubernetes.io/name: createos-api
    app.kubernetes.io/part-of: techchallenge-oficina
type: Opaque
stringData:
  DatabaseSettings__ConnectionString: "Host=postgres;Port=5432;Database=oficina;Username=sa;Password=P@ssw0rd123"
  ResendSettings__ApiKey: "change-me"
